baseURL = "https://us.shoogle.net/washington"
languageCode = "en-US"
title = "Washington"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "washington"
